FROM node:lts

ARG PORT
ENV PORT=$PORT
ARG MYSQL_HOST
ENV MYSQL_HOST=$MYSQL_HOST
ARG MYSQL_USER
ENV MYSQL_USER=$MYSQL_USER
ARG MYSQL_PASSWORD
ENV MYSQL_PASSWORD=$MYSQL_PASSWORD
ARG MYSQL_DB
ENV MYSQL_DB=$MYSQL_DB

WORKDIR /base
COPY *.json ./
RUN npm -i install
COPY . .

EXPOSE $PORT
CMD ["npm", "run", "start"]
